### ISSUE TITLE
bug: quickemu fails on detection of "~Public" on macOS

### ISSUE THREAD

**Issue by JeremiahCornelius** [quickemu-project/quickemu#627]
I'm running quickemu on a 2020 MacBook Pro 13" (Intel), the latest updates of MacOS Ventura, and fully updated homebrew with all dependencies, including bash v. 5.2.15.
`Darwin <hostname> 22.3.0 Darwin Kernel Version 22.3.0: Thu Jan  5 20:53:49 PST 2023; root:xnu-8792.81.2~2/RELEASE_X86_64 x86_64`

quickemu should start a VM from command line such as:
`$ quickemu --vm ubuntu-22.04.conf` 

Instead, during VM creation, an error message is produced:
`ERROR! Public directory: '' doesn't exist!`

- I've stepped through the script/code to locate the detection logic, and nothing seems out-of-place.
- I commented out all areas related to "Public" share, but this causes other exit errors. Reversed changes by replacing from github.
- I've also ensured 777 permissions on ~/Public.
- Considering there may be a samba issue, I enabled "File Sharing" in the MacOS Control Panel.

The time otherwise used by manually configuring qemu guests is considerably reduced by quickemu. I'm at the end of my ability, however, in getting this working on my Mac hosts.

Has this issue been observed by others? I don't see another issue published. Expert assistance here is welcome.

**Comment by JeremiahCornelius** [comment]
THIS IS SOLVED.
The detection doesn't work in the script, but I can force the variable with the command option: --public-dir
`quickemu --public-dir /Users/<user-name>/Public --vm ubuntu-22.04.conf`

This should still be fixed in future releases, for auto-detection on Ventura/Intel.

**Comment by oldman20** [comment]
> THIS IS SOLVED. The detection doesn't work in the script, but I can force the variable with the command option: --public-dir `quickemu --public-dir /Users/<user-name>/Public --vm ubuntu-22.04.conf`
> 
> This should still be fixed in future releases, for auto-detection on Ventura/Intel.

how can u install Quickemu in macOS? I mean what command did u run on macOS? I tried many way but still fail

**Comment by martin-braun** [comment]
@oldman20 put `alias quickemu="quickemu --public-dir $HOME/Public"` in your `.zshrc`, but the problems won't end. ;)
